[book]
authors = ["Adrien Derobert-Mazure"]
language = "en"
multilingual = false
src = "src"
title = "NumaHOP Documetation"

[build]
create-missing = false
extra-watch-dirs = ["gen", "theme"]

[preprocessor.footnote]
[preprocessor.mermaid]
command = "mdbook-mermaid"


[output.html]
theme = "theme"
default-theme = "numahop"
preferred-dark-theme = "numahop"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
