[book]
authors = ["Adrien Derobert-Mazure"]
language = "en"
multilingual = false
src = "build-src"
title = "NumaHOP Documentation"

[build]
create-missing = false
extra-watch-dirs = ["include", "theme", "src", "build-src"]

[preprocessor.mdbook-mermaid]
command = "mdbook-mermaid"

[output.html.fold]
enable = true 
level = 0 

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "dark"
additional-js = ["mermaid.min.js", "mermaid-init.js"]
additional-css = ["./theme/nh-ext.css"]
git-repository-url = "https://github.com/biblibre/NumaHOP-doc" 
git-repository-icon = "fa-github"
