[book]
authors = ["Adrien Derobert-Mazure"]
language = "en"
multilingual = false
src = "src"
title = "NumaHOP Documetation"

[build]
create-missing = false

[preprocessor.footnote]
[preprocessor.mermaid]
command = "mdbook-mermaid"


[output.html]
additional-js = ["mermaid.min.js", "mermaid-init.js"]
