mindmap
    root(NumaHOP)
        Inputs
            Images<br>and<br>MetaData
                {{Digitization<br>Provider}}
                )IIIF(
            Images
            MetaData
                )XML TEI(
                Need External Conversion
                    MarcXML
                    {{Koha}}
                    {{Horizon}}
                    {{ALMA}}
                    {{OpenRefine}}
              EAD
                  {{Calames}}
              CSV
                  Manual<br>Creation
              )JSON(
                  {{IIIF}}
      Outputs
          Sftp
              {{OmekaS}}
              {{CINES}}
              )Cantaloup(
              {{Limgalery}}
          S3
              {{Internet<br>Archive}}
              )S3 Buckets(
                  {{OmekaS}}
          )IIIF(

